apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: asauer/react:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: react-app-config
            - secretRef:
                name: react-app-secret
