apiVersion: v1
kind: Pod
metadata:
  name: kaniko-angular
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--context=git://github.com/assafsauer/react-base.git#refs/heads/main"
   # - "--context-sub-path=react" 
    - "--destination=asauer/react:latest"
#    env:
#      - name: GIT_PASSWORD
#        valueFrom:
#          secretKeyRef:
#            name: gitlabtoken
#            key: password
#      - name: GIT_USERNAME
#        valueFrom:
#          secretKeyRef:
#            name: gitlabtoken
#            key: username
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
  - name: kaniko-secret
    secret:
      secretName: dockercred 
      items:
        - key: .dockerconfigjson
          path: config.json
